### ISSUE TITLE
On-Prem TFS

### ISSUE THREAD

**Issue by parvski** [XpiritBV/Xpirit-Vsts-Release-Settings#3]
Is task available for on-prem TFS?

**Comment by pascalnaber** [comment]
It's possible to download the task for use on on-prem TFS. You can download it here. https://marketplace.visualstudio.com/items?itemName=pascalnaber.PascalNaber-Xpirit-WebAppConfiguration

Though I've only tested this task in VSTS. So please let me know if it works or not on on-prem TFS.

**Comment by hdesouky** [comment]
Installing the extension on TFS on-prem thrown the following exception

> TF53010: The following error has occurred in a Team Foundation component or extension:
> Date (UTC): 11/1/2016 7:42:43 AM
> Machine: TFS
> Application Domain: /LM/W3SVC/2/ROOT-1-131224573183247824
> Assembly: Microsoft.TeamFoundation.Framework.Server, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
> Service Host: 07faeb4a-e6d1-4b04-bb07-eac928e32bc2 (TEAM FOUNDATION)
> Process Details:
>   Process Name: w3wp
>   Process Id: 3676
>   Thread Id: 1276
>   Account name: NEBRASTECH\hdesouky
> 
> Detailed Message: TF30065: An unhandled exception occurred.
> 
> Web Request Details
>     Url: http://tfs:8080/_gallery/items/pascalnaber.PascalNaber-Xpirit-WebAppConfiguration?targetId=dc1dbb49-b483-48fc-8620-bf0e8fc4741d [method: GET]
>     User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
>     Headers: not available
>     Path: /_gallery/items/pascalnaber.PascalNaber-Xpirit-WebAppConfiguration
>     Local Request: False
>     Host Address: 10.0.10.25
>     User: NEBRASTECH\hdesouky [authentication type: Negotiate]
> 
> Exception Message: This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet. (type InvalidOperationException)
> Exception Stack Trace:    at System.Web.Mvc.JsonResult.ExecuteResult(ControllerContext context)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>    at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>    at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>    at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>    at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
>    at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
>    at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
>    at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by jessehouwing** [comment]
I tried on TFS 2017 and there it installs fine. Can you install any other extensions without issue? e.g. https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks

**Comment by jessehouwing** [comment]
Could you share the exact step (preferably with screenshots) where installation fails?
